"""HP/Agilent/Keysight 34401A production test-line driver (spec v1.2.8)."""

from __future__ import annotations

__version__ = "1.2.8"

from .config import (
    ContinuousLoggerConfig,
    DriverConfig,
    SerialRs232Config,
    StabilityProfile,
    VisaGpibConfig,
)
from .driver import Hp34401A, estimate_measurement_timeout_s
from .enums import (
    AcFilterHz,
    Aperture,
    AutoRange,
    AutozeroMode,
    CommandState,
    InputTerminal,
    MeasurementFunction,
    Nplc,
    TransportType,
    TriggerSource,
)
from .errors import (
    CommandError,
    DeviceError,
    ExecutionError,
    Hp34401AError,
    InstrumentConnectionError,
    InstrumentTimeoutError,
    MeasurementNotStableError,
    OverloadError,
    ProtocolError,
    QueryError,
    RecoveryError,
    SafetyError,
    ScpiError,
    TransportError,
)
from .measurement import (
    ErrorRecord,
    HealthReport,
    Identity,
    InstrumentMetadata,
    MeasurementReading,
    RecoveryReport,
    SelfTestResult,
    StableMeasurementResult,
    TestSequenceResult,
    TestStepResult,
)
from .production import TestSequence, TestStep, check_limits, run_measurement_step, run_sequence
from .stability import read_stable_resistance
from .transports import FakeTransport, Transport

__all__ = [
    "AcFilterHz",
    "Aperture",
    "AutoRange",
    "AutozeroMode",
    "CommandError",
    "CommandState",
    "ContinuousLoggerConfig",
    "DeviceError",
    "DriverConfig",
    "ErrorRecord",
    "ExecutionError",
    "FakeTransport",
    "HealthReport",
    "Hp34401A",
    "Hp34401AError",
    "Identity",
    "InputTerminal",
    "InstrumentConnectionError",
    "InstrumentMetadata",
    "InstrumentTimeoutError",
    "MeasurementFunction",
    "MeasurementNotStableError",
    "MeasurementReading",
    "Nplc",
    "OverloadError",
    "ProtocolError",
    "QueryError",
    "RecoveryError",
    "RecoveryReport",
    "SafetyError",
    "ScpiError",
    "SelfTestResult",
    "SerialRs232Config",
    "StabilityProfile",
    "StableMeasurementResult",
    "TestSequence",
    "TestSequenceResult",
    "TestStep",
    "TestStepResult",
    "Transport",
    "TransportError",
    "TransportType",
    "TriggerSource",
    "VisaGpibConfig",
    "__version__",
    "check_limits",
    "estimate_measurement_timeout_s",
    "read_stable_resistance",
    "run_measurement_step",
    "run_sequence",
]
